name: update-twitter-feed


on:
  schedule:
    - cron: '0 * * * *'


jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependency
        run: python -m pip install imgkit
      - name: Change directory
        run: cd data-science-notes
      - name: Update feed
        run: python ./data-science-notes/twitterfeed.py
      - name: Setup git config
        run: |
          git config user.name "Twitter Action"
          git config user.email "<>"
      - name: Commit
          run: |
            git add feed.jpg
            git commit -m "Updated Twitter feed"
            git push origin master